---
project:
  type: website
  output-dir: _site
  pre-render: prepare.py

website:
  title: "USSR GDP Growth Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
      - href: periods.qmd
        text: Period Analysis
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
    df-print: paged

execute:
  warning: false
  error: false
  message: false
  silent: true
